### ISSUE TITLE
sometimes Emojis and Icons get translated

### ISSUE THREAD

**Issue by 1muen** [mozilla/firefox-translations#514]
**Describe the bug**
sometimes Emojis and Icons get translated, if they are font

**To Reproduce**
1. Go to https://developer.microsoft.com/en-us/fluentui#/controls/web/icon
2. Activate Translation

https://user-images.githubusercontent.com/49640488/191548637-70bea497-422d-4b87-b337-fa2b9cba0ae7.mp4

or

1. Go to https://emojipedia.org/
2. Activate Translation

https://user-images.githubusercontent.com/49640488/191548684-656b7c9d-9157-438b-ab9d-f5d4982ee335.mp4

**Expected behavior**
Dont translate icons and emojis. Even tough they are distributed as fonts.

**Screenshots**

**Desktop (please complete the following information as possible):**
- Firefox Browser version: 105.0b9 (64-Bit)
- Processor information:
- OS version:
- System type (32-bit or 64-bit):
- Firefox Translation Extension version:
Version
1.1.4buildid20220803.111909
Zuletzt aktualisiert
9. September 2022
- Webpage on which issue was observed:
- Language of the webpage:English
- Translating to (language):German
- Console logs from Web Developer Tools:
Fluent UI:
```
Using fallback gemm implementation [bergamot-translator-worker.js:2965:17](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/controller/translation/bergamot-translator-worker.js)
Wasm Runtime initialized Successfully (preRun -> onRuntimeInitialized) in 0.006 secs [translationWorker.js:83:29](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/controller/translation/translationWorker.js)
Creating Translation Service with config: {"cacheSize":0} [translationWorker.js:358:25](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/controller/translation/translationWorker.js)
Translation Service created successfully [translationWorker.js:360:25](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/controller/translation/translationWorker.js)
Constructing translation model esen [translationWorker.js:388:21](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/controller/translation/translationWorker.js)
Constructing translation model ende [translationWorker.js:388:21](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/controller/translation/translationWorker.js)
Translation Model config: 
            beam-size: 1
            normalize: 1.0
            word-penalty: 0
            max-length-break: 128
            mini-batch-words: 1024
            workspace: 128
            max-length-factor: 2.0
            skip-cost: false
            cpu-threads: 0
            quiet: true
            quiet-translation: true
            gemm-precision: int8shiftAlphaAll
            alignment: soft
            [translationWorker.js:450:21](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/controller/translation/translationWorker.js)
Aligned memory sizes: Model:17140835, Shortlist:3943644,  Vocab: 784269 [translationWorker.js:451:21](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/controller/translation/translationWorker.js)
Translation Model config: 
            beam-size: 1
            normalize: 1.0
            word-penalty: 0
            max-length-break: 128
            mini-batch-words: 1024
            workspace: 128
            max-length-factor: 2.0
            skip-cost: false
            cpu-threads: 0
            quiet: true
            quiet-translation: true
            gemm-precision: int8shiftAlphaAll
            alignment: soft
            [translationWorker.js:450:21](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/controller/translation/translationWorker.js)
Aligned memory sizes: Model:17140755, Shortlist:3860888,  Vocab: 825463 [translationWorker.js:451:21](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/controller/translation/translationWorker.js)
Model 'esde' successfully constructed. Time taken: 0.28 secs [translationWorker.js:327:23](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/controller/translation/translationWorker.js)
loadLanguageModel function complete [translationWorker.js:350:21](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/controller/translation/translationWorker.js)
[InPlaceTranslation] /SPAN.ms-Dropdown-caretDownWrapper.caretDownWrapper-250 Child <span class="ms-Dropdown-caretDownWrapper caretDownWrapper-250" data-x-bergamot-id="1"><i data-icon-name="ChevronDown" aria-hidden="true" class="ms-Dropdown-caretDown caretDown-266" data-x-bergamot-id="2"><font x-bergamot-sentence-index="0" x-bergamot-sentence-score="-0.287468"></font></i></span> has no text but counterpart <span class="ms-Dropdown-caretDownWrapper caretDownWrapper-250" data-x-bergamot-id="1"><i data-icon-name="ChevronDown" aria-hidden="true" class="ms-Dropdown-caretDown caretDown-266" data-x-bergamot-id="2"></i></span> does [InPageTranslation.js:831:37](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/view/js/InPageTranslation.js)
[InPlaceTranslation] /#document-fragment/SPAN.ms-Button-flexContainer.flexContainer-226/I.ms-Icon.root-89.css-154.ms-Button-icon.icon-228 Child <i data-icon-name="Embed" aria-hidden="true" class="ms-Icon root-89 css-154 ms-Button-icon icon-228" style="font-family: &quot;FabricMDL2Icons&quot;;" data-x-bergamot-id="1"></i> has no text but counterpart <i data-icon-name="Embed" aria-hidden="true" class="ms-Icon root-89 css-154 ms-Button-icon icon-228" style="font-family: &quot;FabricMDL2Icons&quot;;" data-x-bergamot-id="1"></i> does [InPageTranslation.js:831:37](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/view/js/InPageTranslation.js)
[InPlaceTranslation] /I.ms-Icon.root-89.css-247.css-208 Child <i data-icon-name="Dictionary" role="img" aria-label="Dictionary" class="ms-Icon root-89 css-247 css-208" style="font-family: &quot;FabricMDL2Icons-1&quot;;" data-x-bergamot-id="1"></i> has no text but counterpart <i data-icon-name="Dictionary" role="img" aria-label="Dictionary" class="ms-Icon root-89 css-247 css-208" style="font-family: &quot;FabricMDL2Icons-1&quot;;" data-x-bergamot-id="1"></i> does [InPageTranslation.js:831:37](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/view/js/InPageTranslation.js)
[InPlaceTranslation] /I.ms-Icon.root-89.css-271.css-208 Child <i data-icon-name="TrainSolid" role="img" aria-label="Train" class="ms-Icon root-89 css-271 css-208" style="font-family: &quot;FabricMDL2Icons-4&quot;;" data-x-bergamot-id="2"><font x-bergamot-sentence-index="0" x-bergamot-sentence-score="-0.0339756"></font></i> has no text but counterpart <i data-icon-name="TrainSolid" role="img" aria-label="Train" class="ms-Icon root-89 css-271 css-208" style="font-family: &quot;FabricMDL2Icons-4&quot;;" data-x-bergamot-id="2"></i> does [InPageTranslation.js:831:37](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/view/js/InPageTranslation.js)
[InPlaceTranslation] /SPAN.ms-Dropdown-caretDownWrapper.caretDownWrapper-250 Child <span class="ms-Dropdown-caretDownWrapper caretDownWrapper-250" data-x-bergamot-id="1"><i data-icon-name="ChevronDown" aria-hidden="true" class="ms-Dropdown-caretDown caretDown-266" data-x-bergamot-id="2"><font x-bergamot-sentence-index="0" x-bergamot-sentence-score="-0.282427"></font></i></span> has no text but counterpart <span class="ms-Dropdown-caretDownWrapper caretDownWrapper-250" data-x-bergamot-id="1"><i data-icon-name="ChevronDown" aria-hidden="true" class="ms-Dropdown-caretDown caretDown-266" data-x-bergamot-id="2"></i></span> does [InPageTranslation.js:831:37](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/view/js/InPageTranslation.js)
[InPlaceTranslation] /#document-fragment/SPAN.ms-Button-flexContainer.flexContainer-226/I.ms-Icon.root-89.css-154.ms-Button-icon.icon-228 Child <i data-icon-name="Embed" aria-hidden="true" class="ms-Icon root-89 css-154 ms-Button-icon icon-228" style="font-family: &quot;FabricMDL2Icons&quot;;" data-x-bergamot-id="1"></i> has no text but counterpart <i data-icon-name="Embed" aria-hidden="true" class="ms-Icon root-89 css-154 ms-Button-icon icon-228" style="font-family: &quot;FabricMDL2Icons&quot;;" data-x-bergamot-id="1"></i> does [InPageTranslation.js:831:37](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/view/js/InPageTranslation.js)
[InPlaceTranslation] /#document-fragment/LI.section_c9f631a8/DIV.ms-CollapsibleSection.css-162/BUTTON.css-165/SPAN.css-167 Child <span class="css-167" data-x-bergamot-id="4"><font x-bergamot-sentence-index="0" x-bergamot-sentence-score="-1.53993"></font></span> has no text but counterpart <span class="css-167" data-x-bergamot-id="4">Basic Inputs</span> does [InPageTranslation.js:831:37](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/view/js/InPageTranslation.js)
[InPlaceTranslation] /#document-fragment/LI.section_c9f631a8/DIV.ms-CollapsibleSection.css-162/BUTTON.css-165/I.root-166 Child <i data-icon-name="ChevronDown" aria-hidden="true" class="root-166" data-x-bergamot-id="8"></i> has no text but counterpart <i data-icon-name="ChevronDown" aria-hidden="true" class="root-166" data-x-bergamot-id="8"></i> does [InPageTranslation.js:831:37](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/view/js/InPageTranslation.js)
[InPlaceTranslation] /#document-fragment/LI.section_c9f631a8/DIV.ms-CollapsibleSection.css-162/BUTTON.css-165/I.root-166 Child <i data-icon-name="ChevronDown" aria-hidden="true" class="root-166" data-x-bergamot-id="18"></i> has no text but counterpart <i data-icon-name="ChevronDown" aria-hidden="true" class="root-166" data-x-bergamot-id="18"></i> does [InPageTranslation.js:831:37](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/view/js/InPageTranslation.js)
[InPlaceTranslation] /#document-fragment/LI.section_c9f631a8/DIV.ms-CollapsibleSection.css-162/BUTTON.css-165/SPAN.css-167 Child <span class="css-167" data-x-bergamot-id="29"><font x-bergamot-sentence-index="5" x-bergamot-sentence-score="-0.436311"></font></span> has no text but counterpart <span class="css-167" data-x-bergamot-id="29">Progress</span> does [InPageTranslation.js:831:37](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/view/js/InPageTranslation.js)
[InPlaceTranslation] /#document-fragment/LI.section_c9f631a8/DIV.ms-CollapsibleSection.css-162/BUTTON.css-165/SPAN.css-167 Child <span class="css-167" data-x-bergamot-id="34"><font x-bergamot-sentence-index="6" x-bergamot-sentence-score="-0.638854"></font></span> has no text but counterpart <span class="css-167" data-x-bergamot-id="34">Surfaces</span> does [InPageTranslation.js:831:37](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/view/js/InPageTranslation.js)
[InPlaceTranslation] /#document-fragment/LI.section_c9f631a8.hasActiveChild_c9f631a8/DIV.ms-CollapsibleSection.css-162/BUTTON.css-165/SPAN.css-167 Child <span class="css-167" data-x-bergamot-id="39"><font x-bergamot-sentence-index="7" x-bergamot-sentence-score="-1.04695"></font></span> has no text but counterpart <span class="css-167" data-x-bergamot-id="39">Utilities</span> does [InPageTranslation.js:831:37](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/view/js/InPageTranslation.js)
[InPlaceTranslation] /#document-fragment/LI.section_c9f631a8.hasActiveChild_c9f631a8/DIV.ms-CollapsibleSection.css-162/DIV.ms-CollapsibleSection-body/UL.links_c9f631a8/LI.section_c9f631a8/DIV.ms-CollapsibleSection.css-162/BUTTON.css-165/I.root-166 Child <i data-icon-name="ChevronDown" aria-hidden="true" class="root-166" data-x-bergamot-id="45"></i> has no text but counterpart <i data-icon-name="ChevronDown" aria-hidden="true" class="root-166" data-x-bergamot-id="45"></i> does [InPageTranslation.js:831:37](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/view/js/InPageTranslation.js)
[InPlaceTranslation] /#document-fragment/LI.section_c9f631a8/DIV.ms-CollapsibleSection.css-162/BUTTON.css-165/SPAN.css-167 Child <span class="css-167" data-x-bergamot-id="83"><font x-bergamot-sentence-index="25" x-bergamot-sentence-score="-0.180473"></font></span> has no text but counterpart <span class="css-167" data-x-bergamot-id="83">References</span> does [InPageTranslation.js:831:37](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/view/js/InPageTranslation.js)
[InPlaceTranslation] /#document-fragment/SPAN.ms-Button-flexContainer.flexContainer-226/I.ms-Icon.root-89.css-154.ms-Button-menuIcon.menuIcon-229 Child <i data-icon-name="ChevronDown" aria-hidden="true" class="ms-Icon root-89 css-154 ms-Button-menuIcon menuIcon-229" style="font-family: &quot;FabricMDL2Icons&quot;;" data-x-bergamot-id="3"><font x-bergamot-sentence-index="0" x-bergamot-sentence-score="-0.175489"></font></i> has no text but counterpart <i data-icon-name="ChevronDown" aria-hidden="true" class="ms-Icon root-89 css-154 ms-Button-menuIcon menuIcon-229" style="font-family: &quot;FabricMDL2Icons&quot;;" data-x-bergamot-id="3"></i> does [InPageTranslation.js:831:37](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/view/js/InPageTranslation.js)
[InPlaceTranslation] /I.ms-Icon.root-89.css-247.greenYellow-210 Child <i data-icon-name="Dictionary" role="img" aria-label="Dictionary" class="ms-Icon root-89 css-247 greenYellow-210" style="font-family: &quot;FabricMDL2Icons-1&quot;;" data-x-bergamot-id="1"></i> has no text but counterpart <i data-icon-name="Dictionary" role="img" aria-label="Dictionary" class="ms-Icon root-89 css-247 greenYellow-210" style="font-family: &quot;FabricMDL2Icons-1&quot;;" data-x-bergamot-id="1"></i> does [InPageTranslation.js:831:37](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/view/js/InPageTranslation.js)
[InPlaceTranslation] /I.ms-Icon.root-89.css-271.salmon-211 Child <i data-icon-name="TrainSolid" role="img" aria-label="Train" class="ms-Icon root-89 css-271 salmon-211" style="font-family: &quot;FabricMDL2Icons-4&quot;;" data-x-bergamot-id="2"><font x-bergamot-sentence-index="0" x-bergamot-sentence-score="-0.0339756"></font></i> has no text but counterpart <i data-icon-name="TrainSolid" role="img" aria-label="Train" class="ms-Icon root-89 css-271 salmon-211" style="font-family: &quot;FabricMDL2Icons-4&quot;;" data-x-bergamot-id="2"></i> does [InPageTranslation.js:831:37](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/view/js/InPageTranslation.js)
[InPlaceTranslation] /SPAN.ms-Dropdown-caretDownWrapper.caretDownWrapper-250 Child <span class="ms-Dropdown-caretDownWrapper caretDownWrapper-250" data-x-bergamot-id="1"><i data-icon-name="ChevronDown" aria-hidden="true" class="ms-Dropdown-caretDown caretDown-266" data-x-bergamot-id="2"><font x-bergamot-sentence-index="0" x-bergamot-sentence-score="-0.282427"></font></i></span> has no text but counterpart <span class="ms-Dropdown-caretDownWrapper caretDownWrapper-250" data-x-bergamot-id="1"><i data-icon-name="ChevronDown" aria-hidden="true" class="ms-Dropdown-caretDown caretDown-266" data-x-bergamot-id="2"></i></span> does [InPageTranslation.js:831:37](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/view/js/InPageTranslation.js)
[InPlaceTranslation] /#document-fragment/SPAN.ms-Button-flexContainer.flexContainer-226/I.ms-Icon.root-89.css-154.ms-Button-icon.icon-228 Child <i data-icon-name="Embed" aria-hidden="true" class="ms-Icon root-89 css-154 ms-Button-icon icon-228" style="font-family: &quot;FabricMDL2Icons&quot;;" data-x-bergamot-id="1"></i> has no text but counterpart <i data-icon-name="Embed" aria-hidden="true" class="ms-Icon root-89 css-154 ms-Button-icon icon-228" style="font-family: &quot;FabricMDL2Icons&quot;;" data-x-bergamot-id="1"></i> does [InPageTranslation.js:831:37](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/view/js/InPageTranslation.js)
[InPlaceTranslation] /SPAN.ms-Dropdown-caretDownWrapper.caretDownWrapper-250 Child <span class="ms-Dropdown-caretDownWrapper caretDownWrapper-250" data-x-bergamot-id="1"><i data-icon-name="ChevronDown" aria-hidden="true" class="ms-Dropdown-caretDown caretDown-266" data-x-bergamot-id="2"><font x-bergamot-sentence-index="0" x-bergamot-sentence-score="-0.278183"></font></i></span> has no text but counterpart <span class="ms-Dropdown-caretDownWrapper caretDownWrapper-250" data-x-bergamot-id="1"><i data-icon-name="ChevronDown" aria-hidden="true" class="ms-Dropdown-caretDown caretDown-266" data-x-bergamot-id="2"></i></span> does [InPageTranslation.js:831:37](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/view/js/InPageTranslation.js)
[InPlaceTranslation] /#document-fragment/SPAN.ms-Button-flexContainer.flexContainer-226/I.ms-Icon.root-89.css-154.ms-Button-icon.icon-228 Child <i data-icon-name="Embed" aria-hidden="true" class="ms-Icon root-89 css-154 ms-Button-icon icon-228" style="font-family: &quot;FabricMDL2Icons&quot;;" data-x-bergamot-id="1"></i> has no text but counterpart <i data-icon-name="Embed" aria-hidden="true" class="ms-Icon root-89 css-154 ms-Button-icon icon-228" style="font-family: &quot;FabricMDL2Icons&quot;;" data-x-bergamot-id="1"></i> does [InPageTranslation.js:831:37](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/view/js/InPageTranslation.js)
[InPlaceTranslation] /SPAN.ms-Dropdown-caretDownWrapper.caretDownWrapper-250 Child <span class="ms-Dropdown-caretDownWrapper caretDownWrapper-250" data-x-bergamot-id="1"><i data-icon-name="ChevronDown" aria-hidden="true" class="ms-Dropdown-caretDown caretDown-266" data-x-bergamot-id="2"><font x-bergamot-sentence-index="0" x-bergamot-sentence-score="-0.278183"></font></i></span> has no text but counterpart <span class="ms-Dropdown-caretDownWrapper caretDownWrapper-250" data-x-bergamot-id="1"><i data-icon-name="ChevronDown" aria-hidden="true" class="ms-Dropdown-caretDown caretDown-266" data-x-bergamot-id="2"></i></span> does [InPageTranslation.js:831:37](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/view/js/InPageTranslation.js)
[InPlaceTranslation] /#document-fragment/SPAN.ms-Button-flexContainer.flexContainer-226/I.ms-Icon.root-89.css-154.ms-Button-icon.icon-228 Child <i data-icon-name="Embed" aria-hidden="true" class="ms-Icon root-89 css-154 ms-Button-icon icon-228" style="font-family: &quot;FabricMDL2Icons&quot;;" data-x-bergamot-id="1"></i> has no text but counterpart <i data-icon-name="Embed" aria-hidden="true" class="ms-Icon root-89 css-154 ms-Button-icon icon-228" style="font-family: &quot;FabricMDL2Icons&quot;;" data-x-bergamot-id="1"></i> does [InPageTranslation.js:831:37](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/view/js/InPageTranslation.js)
Unexpected exception sending payload. Ex:[object Error]{ stack: 'o@https://partnerresources.azureedge.net/public/2022.9.1.2/scripts/partner.min.js:1:5359
i.prototype.instrumentSend/XMLHttpRequest.prototype.send@https://partnerresources.azureedge.net/public/2022.9.1.2/scripts/ai.min.js:1:43821
u@https://js.monitor.azure.com/scripts/c/ms.analytics-web-3.gbl.min.js:6:50772
o@https://js.monitor.azure.com/scripts/c/ms.analytics-web-3.gbl.min.js:6:54975
hc/</v/</<@https://js.monitor.azure.com/scripts/c/ms.analytics-web-3.gbl.min.js:6:55634
Mi@https://js.monitor.azure.com/scripts/c/ms.analytics-web-3.gbl.min.js:6:13997
hc/</v/<@https://js.monitor.azure.com/scripts/c/ms.analytics-web-3.gbl.min.js:6:55117
Mi@https://js.monitor.azure.com/scripts/c/ms.analytics-web-3.gbl.min.js:6:13997
v@https://js.monitor.azure.com/scripts/c/ms.analytics-web-3.gbl.min.js:6:53334
hc/</T/<@https://js.monitor.azure.com/scripts/c/ms.analytics-web-3.gbl.min.js:6:52128
Mi@https://js.monitor.azure.com/scripts/c/ms.analytics-web-3.gbl.min.js:6:13997
T@https://js.monitor.azure.com/scripts/c/ms.analytics-web-3.gbl.min.js:6:51675
hc/</m.sendQueuedRequests@https://js.monitor.azure.com/scripts/c/ms.analytics-web-3.gbl.min.js:6:57700
a@https://js.monitor.azure.com/scripts/c/ms.analytics-web-3.gbl.min.js:6:59690
Ac/</o/W<@https://js.monitor.azure.com/scripts/c/ms.analytics-web-3.gbl.min.js:6:59898
', message: 'JSON.parse: expected ',' or ']' after array element at line 1 column 2373 of the JSON data', name: 'SyntaxError' [DiagnosticLogger.js:40:32](https://js.monitor.azure.com/common/temp/node_modules/@microsoft/applicationinsights-core-js/dist-esm/JavaScriptSDK/DiagnosticLogger.js)
Unexpected exception sending payload. Ex:[object Error]{ stack: 'o@https://partnerresources.azureedge.net/public/2022.9.1.2/scripts/partner.min.js:1:5359
i.prototype.instrumentSend/XMLHttpRequest.prototype.send@https://partnerresources.azureedge.net/public/2022.9.1.2/scripts/ai.min.js:1:43821
u@https://js.monitor.azure.com/scripts/c/ms.analytics-web-3.gbl.min.js:6:50772
o@https://js.monitor.azure.com/scripts/c/ms.analytics-web-3.gbl.min.js:6:54975
hc/</v/</<@https://js.monitor.azure.com/scripts/c/ms.analytics-web-3.gbl.min.js:6:55634
Mi@https://js.monitor.azure.com/scripts/c/ms.analytics-web-3.gbl.min.js:6:13997
hc/</v/<@https://js.monitor.azure.com/scripts/c/ms.analytics-web-3.gbl.min.js:6:55117
Mi@https://js.monitor.azure.com/scripts/c/ms.analytics-web-3.gbl.min.js:6:13997
v@https://js.monitor.azure.com/scripts/c/ms.analytics-web-3.gbl.min.js:6:53334
hc/</T/<@https://js.monitor.azure.com/scripts/c/ms.analytics-web-3.gbl.min.js:6:52128
Mi@https://js.monitor.azure.com/scripts/c/ms.analytics-web-3.gbl.min.js:6:13997
T@https://js.monitor.azure.com/scripts/c/ms.analytics-web-3.gbl.min.js:6:51675
hc/</v/</o/t/<@https://js.monitor.azure.com/scripts/c/ms.analytics-web-3.gbl.min.js:6:54458
', message: 'JSON.parse: expected ',' or ']' after array element at line 1 column 2373 of the JSON data', name: 'SyntaxError' [DiagnosticLogger.js:40:32](https://js.monitor.azure.com/common/temp/node_modules/@microsoft/applicationinsights-core-js/dist-esm/JavaScriptSDK/DiagnosticLogger.js)
[InPlaceTranslation] /#document-fragment/LI.section_c9f631a8/DIV.ms-CollapsibleSection.css-162/BUTTON.css-165/I.root-166 Child <i data-icon-name="ChevronDown" aria-hidden="true" class="root-166" data-x-bergamot-id="3"></i> has no text but counterpart <i data-icon-name="ChevronDown" aria-hidden="true" class="root-166" data-x-bergamot-id="3"></i> does

System architecture and extension information can be found as follows:
Go to about:telemetry#environment-data in browser and share "architecture" field under "build" category and "cpu.extensions" field under "system" category


```

### emojipedia:
```
Using fallback gemm implementation [bergamot-translator-worker.js:2965:17](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/controller/translation/bergamot-translator-worker.js)
Wasm Runtime initialized Successfully (preRun -> onRuntimeInitialized) in 0.005 secs [translationWorker.js:83:29](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/controller/translation/translationWorker.js)
Creating Translation Service with config: {"cacheSize":0} [translationWorker.js:358:25](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/controller/translation/translationWorker.js)
Translation Service created successfully [translationWorker.js:360:25](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/controller/translation/translationWorker.js)
Constructing translation model esen [translationWorker.js:388:21](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/controller/translation/translationWorker.js)
Constructing translation model ende [translationWorker.js:388:21](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/controller/translation/translationWorker.js)
Translation Model config: 
            beam-size: 1
            normalize: 1.0
            word-penalty: 0
            max-length-break: 128
            mini-batch-words: 1024
            workspace: 128
            max-length-factor: 2.0
            skip-cost: false
            cpu-threads: 0
            quiet: true
            quiet-translation: true
            gemm-precision: int8shiftAlphaAll
            alignment: soft
            [translationWorker.js:450:21](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/controller/translation/translationWorker.js)
Aligned memory sizes: Model:17140755, Shortlist:3860888,  Vocab: 825463 [translationWorker.js:451:21](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/controller/translation/translationWorker.js)
Translation Model config: 
            beam-size: 1
            normalize: 1.0
            word-penalty: 0
            max-length-break: 128
            mini-batch-words: 1024
            workspace: 128
            max-length-factor: 2.0
            skip-cost: false
            cpu-threads: 0
            quiet: true
            quiet-translation: true
            gemm-precision: int8shiftAlphaAll
            alignment: soft
            [translationWorker.js:450:21](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/controller/translation/translationWorker.js)
Aligned memory sizes: Model:17140835, Shortlist:3943644,  Vocab: 784269 [translationWorker.js:451:21](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/controller/translation/translationWorker.js)
Model 'esde' successfully constructed. Time taken: 0.264 secs [translationWorker.js:327:23](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/controller/translation/translationWorker.js)
loadLanguageModel function complete [translationWorker.js:350:21](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/controller/translation/translationWorker.js)
[InPlaceTranslation] /#document-fragment/LI.emoji-navbar-category/A/SPAN Child <span data-x-bergamot-id="2"></span> has no text but counterpart <span data-x-bergamot-id="2">😃</span> does [InPageTranslation.js:831:37](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/view/js/InPageTranslation.js)
[InPlaceTranslation] /#document-fragment/LI.emoji-navbar-category/A/SPAN Child <span data-x-bergamot-id="23"></span> has no text but counterpart <span data-x-bergamot-id="23">🎌</span> does [InPageTranslation.js:831:37](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/view/js/InPageTranslation.js)
[InPlaceTranslation] /#document-fragment/LI/A/SPAN.emoji Child <span class="emoji" data-x-bergamot-id="2"></span> has no text but counterpart <span class="emoji" data-x-bergamot-id="2">🫶</span> does [InPageTranslation.js:831:37](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/view/js/InPageTranslation.js)
[InPlaceTranslation] /#document-fragment/LI/A/SPAN.emoji Child <span class="emoji" data-x-bergamot-id="5"></span> has no text but counterpart <span class="emoji" data-x-bergamot-id="5">❤️</span> does [InPageTranslation.js:831:37](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/view/js/InPageTranslation.js)
[InPlaceTranslation] /#document-fragment/LI/A/SPAN.emoji Child <span class="emoji" data-x-bergamot-id="8"></span> has no text but counterpart <span class="emoji" data-x-bergamot-id="8">😊</span> does [InPageTranslation.js:831:37](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/view/js/InPageTranslation.js)
[InPlaceTranslation] /#document-fragment/LI/A/SPAN.emoji Child <span class="emoji" data-x-bergamot-id="11"></span> has no text but counterpart <span class="emoji" data-x-bergamot-id="11">✨</span> does [InPageTranslation.js:831:37](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/view/js/InPageTranslation.js)
[InPlaceTranslation] /#document-fragment/LI/A/SPAN.emoji Child <span class="emoji" data-x-bergamot-id="14"></span> has no text but counterpart <span class="emoji" data-x-bergamot-id="14">🥹</span> does [InPageTranslation.js:831:37](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/view/js/InPageTranslation.js)
[InPlaceTranslation] /#document-fragment/LI/A/SPAN.emoji Child <span class="emoji" data-x-bergamot-id="2"></span> has no text but counterpart <span class="emoji" data-x-bergamot-id="2">🪔</span> does [InPageTranslation.js:831:37](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/view/js/InPageTranslation.js)
[InPlaceTranslation] /#document-fragment/LI/A/SPAN.emoji Child <span class="emoji" data-x-bergamot-id="5"></span> has no text but counterpart <span class="emoji" data-x-bergamot-id="5">🎃</span> does [InPageTranslation.js:831:37](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/view/js/InPageTranslation.js)
[InPlaceTranslation] /#document-fragment/LI/A/SPAN.emoji Child <span class="emoji" data-x-bergamot-id="8"></span> has no text but counterpart <span class="emoji" data-x-bergamot-id="8">🔥</span> does [InPageTranslation.js:831:37](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/view/js/InPageTranslation.js)
[InPlaceTranslation] /#document-fragment/LI/A/SPAN.emoji Child <span class="emoji" data-x-bergamot-id="2"></span> has no text but counterpart <span class="emoji" data-x-bergamot-id="2">🪟</span> does [InPageTranslation.js:831:37](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/view/js/InPageTranslation.js)
[InPlaceTranslation] /#document-fragment/LI/A/SPAN.emoji Child <span class="emoji" data-x-bergamot-id="5"></span> has no text but counterpart <span class="emoji" data-x-bergamot-id="5">🤯</span> does [InPageTranslation.js:831:37](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/view/js/InPageTranslation.js)
[InPlaceTranslation] /#document-fragment/LI/A/SPAN.emoji Child <span class="emoji" data-x-bergamot-id="11"></span> has no text but counterpart <span class="emoji" data-x-bergamot-id="11">🐷</span> does [InPageTranslation.js:831:37](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/view/js/InPageTranslation.js)
[InPlaceTranslation] /#document-fragment/LI/A/SPAN.emoji Child <span class="emoji" data-x-bergamot-id="14"></span> has no text but counterpart <span class="emoji" data-x-bergamot-id="14">📙</span> does [InPageTranslation.js:831:37](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/view/js/InPageTranslation.js)
[InPlaceTranslation] /A Cloning node 
<a href="/emoji/" title="😃 Every Emoji by Codepoint" data-x-bergamot-id="1">
 because it was already inserted earlier [InPageTranslation.js:817:37](moz-extension://908a28bf-48c6-45cd-8427-50243dfcdb32/view/js/InPageTranslation.js)
[InPlaceTranslation] /A Cloning node 
<a href="#" data-x-bergamot-id="4"> because it was already inserted earlier
```

**Comment by marco-c** [comment]
Moved to Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1842819.
